/**
 * 
 */
function StartFresh() {
	localStorage.clear();
}

/**
 * 
 */
function StorefunctionB() {
			//localStorage.clear();		
			localStorage.setItem("ballsB", document.getElementById('baB').value);
			localStorage.setItem("strikesB", document.getElementById('stB').value);
			localStorage.setItem("foulsB", document.getElementById('fbB').value);
			localStorage.setItem("teamB", document.getElementById('teambot').value);
			localStorage.setItem("pitcherB", document.getElementById('pitcherbot').value);
			localStorage.setItem("rp1B", document.getElementById('rp1B').value);
			localStorage.setItem("rp2B", document.getElementById('rp2B').value);
			localStorage.setItem("rp3B", document.getElementById('rp3B').value);
			localStorage.setItem("rp4B", document.getElementById('rp4B').value);
			localStorage.setItem("rp5B", document.getElementById('rp5B').value);
			localStorage.setItem("rp6B", document.getElementById('rp6B').value);
			localStorage.setItem("1stBot", document.getElementById('1stBot').value);
			localStorage.setItem("2ndBot", document.getElementById('2ndBot').value);
			localStorage.setItem("3rdBot", document.getElementById('3rdBot').value);
			localStorage.setItem("4thBot", document.getElementById('4thBot').value);
			localStorage.setItem("5thBot", document.getElementById('5thBot').value);
			localStorage.setItem("6thBot", document.getElementById('6thBot').value);
			localStorage.setItem("7thBot", document.getElementById('7thBot').value);
			localStorage.setItem("8thBot", document.getElementById('8thBot').value);
			localStorage.setItem("9thBot", document.getElementById('9thBot').value);
			localStorage.setItem("bot1", document.getElementById('bot1').value);
			localStorage.setItem("bot2", document.getElementById('bot2').value);
			localStorage.setItem("bot3", document.getElementById('bot3').value);
			localStorage.setItem("bot4", document.getElementById('bot4').value);
			localStorage.setItem("bot5", document.getElementById('bot5').value);
			localStorage.setItem("bot6", document.getElementById('bot6').value);
			localStorage.setItem("bot7", document.getElementById('bot7').value);
			localStorage.setItem("bot8", document.getElementById('bot8').value);
			localStorage.setItem("bot9", document.getElementById('bot9').value);		
			localStorage.setItem("b1inn1B", document.getElementById('b1inn1B').value);
			localStorage.setItem("b1inn2B", document.getElementById('b1inn2B').value);
			localStorage.setItem("b1inn3B", document.getElementById('b1inn3B').value);
			localStorage.setItem("b1inn4B", document.getElementById('b1inn4B').value);
			localStorage.setItem("b1inn5B", document.getElementById('b1inn5B').value);
			localStorage.setItem("b1inn6B", document.getElementById('b1inn6B').value);
			localStorage.setItem("b1inn7B", document.getElementById('b1inn7B').value);
			localStorage.setItem("b1inn8B", document.getElementById('b1inn8B').value);
			localStorage.setItem("b1inn9B", document.getElementById('b1inn9B').value);
			localStorage.setItem("b1inn10B", document.getElementById('b1inn10B').value);
			localStorage.setItem("b1inn11B", document.getElementById('b1inn11B').value);
			localStorage.setItem("b1inn12B", document.getElementById('b1inn12B').value);			
			localStorage.setItem("b2inn1B", document.getElementById('b2inn1B').value);
			localStorage.setItem("b2inn2B", document.getElementById('b2inn2B').value);
			localStorage.setItem("b2inn3B", document.getElementById('b2inn3B').value);
			localStorage.setItem("b2inn4B", document.getElementById('b2inn4B').value);
			localStorage.setItem("b2inn5B", document.getElementById('b2inn5B').value);
			localStorage.setItem("b2inn6B", document.getElementById('b2inn6B').value);
			localStorage.setItem("b2inn7B", document.getElementById('b2inn7B').value);
			localStorage.setItem("b2inn8B", document.getElementById('b2inn8B').value);
			localStorage.setItem("b2inn9B", document.getElementById('b2inn9B').value);
			localStorage.setItem("b2inn10B", document.getElementById('b2inn10B').value);
			localStorage.setItem("b2inn11B", document.getElementById('b2inn11B').value);
			localStorage.setItem("b2inn12B", document.getElementById('b2inn12B').value);			
			localStorage.setItem("b3inn1B", document.getElementById('b3inn1B').value);
			localStorage.setItem("b3inn2B", document.getElementById('b3inn2B').value);
			localStorage.setItem("b3inn3B", document.getElementById('b3inn3B').value);
			localStorage.setItem("b3inn4B", document.getElementById('b3inn4B').value);
			localStorage.setItem("b3inn5B", document.getElementById('b3inn5B').value);
			localStorage.setItem("b3inn6B", document.getElementById('b3inn6B').value);
			localStorage.setItem("b3inn7B", document.getElementById('b3inn7B').value);
			localStorage.setItem("b3inn8B", document.getElementById('b3inn8B').value);
			localStorage.setItem("b3inn9B", document.getElementById('b3inn9B').value);
			localStorage.setItem("b3inn10B", document.getElementById('b3inn10B').value);
			localStorage.setItem("b3inn11B", document.getElementById('b3inn11B').value);
			localStorage.setItem("b3inn12B", document.getElementById('b3inn12B').value);			
			localStorage.setItem("b4inn1B", document.getElementById('b4inn1B').value);
			localStorage.setItem("b4inn2B", document.getElementById('b4inn2B').value);
			localStorage.setItem("b4inn3B", document.getElementById('b4inn3B').value);
			localStorage.setItem("b4inn4B", document.getElementById('b4inn4B').value);
			localStorage.setItem("b4inn5B", document.getElementById('b4inn5B').value);
			localStorage.setItem("b4inn6B", document.getElementById('b4inn6B').value);
			localStorage.setItem("b4inn7B", document.getElementById('b4inn7B').value);
			localStorage.setItem("b4inn8B", document.getElementById('b4inn8B').value);
			localStorage.setItem("b4inn9B", document.getElementById('b4inn9B').value);
			localStorage.setItem("b4inn10B", document.getElementById('b4inn10B').value);
			localStorage.setItem("b4inn11B", document.getElementById('b4inn11B').value);
			localStorage.setItem("b4inn12B", document.getElementById('b4inn12B').value);			
			localStorage.setItem("b5inn1B", document.getElementById('b5inn1B').value);
			localStorage.setItem("b5inn2B", document.getElementById('b5inn2B').value);
			localStorage.setItem("b5inn3B", document.getElementById('b5inn3B').value);
			localStorage.setItem("b5inn4B", document.getElementById('b5inn4B').value);
			localStorage.setItem("b5inn5B", document.getElementById('b5inn5B').value);
			localStorage.setItem("b5inn6B", document.getElementById('b5inn6B').value);
			localStorage.setItem("b5inn7B", document.getElementById('b5inn7B').value);
			localStorage.setItem("b5inn8B", document.getElementById('b5inn8B').value);
			localStorage.setItem("b5inn9B", document.getElementById('b5inn9B').value);
			localStorage.setItem("b5inn10B", document.getElementById('b5inn10B').value);
			localStorage.setItem("b5inn11B", document.getElementById('b5inn11B').value);
			localStorage.setItem("b5inn12B", document.getElementById('b5inn12B').value);			
			localStorage.setItem("b6inn1B", document.getElementById('b6inn1B').value);
			localStorage.setItem("b6inn2B", document.getElementById('b6inn2B').value);
			localStorage.setItem("b6inn3B", document.getElementById('b6inn3B').value);
			localStorage.setItem("b6inn4B", document.getElementById('b6inn4B').value);
			localStorage.setItem("b6inn5B", document.getElementById('b6inn5B').value);
			localStorage.setItem("b6inn6B", document.getElementById('b6inn6B').value);
			localStorage.setItem("b6inn7B", document.getElementById('b6inn7B').value);
			localStorage.setItem("b6inn8B", document.getElementById('b6inn8B').value);
			localStorage.setItem("b6inn9B", document.getElementById('b6inn9B').value);
			localStorage.setItem("b6inn10B", document.getElementById('b6inn10B').value);
			localStorage.setItem("b6inn11B", document.getElementById('b6inn11B').value);
			localStorage.setItem("b6inn12B", document.getElementById('b6inn12B').value);			
			localStorage.setItem("b7inn1B", document.getElementById('b7inn1B').value);
			localStorage.setItem("b7inn2B", document.getElementById('b7inn2B').value);
			localStorage.setItem("b7inn3B", document.getElementById('b7inn3B').value);
			localStorage.setItem("b7inn4B", document.getElementById('b7inn4B').value);
			localStorage.setItem("b7inn5B", document.getElementById('b7inn5B').value);
			localStorage.setItem("b7inn6B", document.getElementById('b7inn6B').value);
			localStorage.setItem("b7inn7B", document.getElementById('b7inn7B').value);
			localStorage.setItem("b7inn8B", document.getElementById('b7inn8B').value);
			localStorage.setItem("b7inn9B", document.getElementById('b7inn9B').value);
			localStorage.setItem("b7inn10B", document.getElementById('b7inn10B').value);
			localStorage.setItem("b7inn11B", document.getElementById('b7inn11B').value);
			localStorage.setItem("b7inn12B", document.getElementById('b7inn12B').value);			
			localStorage.setItem("b8inn1B", document.getElementById('b8inn1B').value);
			localStorage.setItem("b8inn2B", document.getElementById('b8inn2B').value);
			localStorage.setItem("b8inn3B", document.getElementById('b8inn3B').value);
			localStorage.setItem("b8inn4B", document.getElementById('b8inn4B').value);
			localStorage.setItem("b8inn5B", document.getElementById('b8inn5B').value);
			localStorage.setItem("b8inn6B", document.getElementById('b8inn6B').value);
			localStorage.setItem("b8inn7B", document.getElementById('b8inn7B').value);
			localStorage.setItem("b8inn8B", document.getElementById('b8inn8B').value);
			localStorage.setItem("b8inn9B", document.getElementById('b8inn9B').value);
			localStorage.setItem("b8inn10B", document.getElementById('b8inn10B').value);
			localStorage.setItem("b8inn11B", document.getElementById('b8inn11B').value);
			localStorage.setItem("b8inn12B", document.getElementById('b8inn12B').value);			
			localStorage.setItem("b9inn1B", document.getElementById('b9inn1B').value);
			localStorage.setItem("b9inn2B", document.getElementById('b9inn2B').value);
			localStorage.setItem("b9inn3B", document.getElementById('b9inn3B').value);
			localStorage.setItem("b9inn4B", document.getElementById('b9inn4B').value);
			localStorage.setItem("b9inn5B", document.getElementById('b9inn5B').value);
			localStorage.setItem("b9inn6B", document.getElementById('b9inn6B').value);
			localStorage.setItem("b9inn7B", document.getElementById('b9inn7B').value);
			localStorage.setItem("b9inn8B", document.getElementById('b9inn8B').value);
			localStorage.setItem("b9inn9B", document.getElementById('b9inn9B').value);
			localStorage.setItem("b9inn10B", document.getElementById('b9inn10B').value);
			localStorage.setItem("b9inn11B", document.getElementById('b9inn11B').value);
			localStorage.setItem("b9inn12B", document.getElementById('b9inn12B').value);		
		}
		
		function recallStoreB() {
			document.getElementById('baB').value = localStorage.getItem("ballsB");
			document.getElementById('stB').value = localStorage.getItem("strikesB");
			document.getElementById('fbB').value = localStorage.getItem("foulsB");
			document.getElementById('teambot').value = localStorage.getItem("teamB");
			document.getElementById('pitcherbot').value = localStorage.getItem("pitcherB");
			document.getElementById('rp1B').value = localStorage.getItem("rp1B");
			document.getElementById('rp2B').value = localStorage.getItem("rp2B");
			document.getElementById('rp3B').value = localStorage.getItem("rp3B");
			document.getElementById('rp4B').value = localStorage.getItem("rp4B");
			document.getElementById('rp5B').value = localStorage.getItem("rp5B");
			document.getElementById('rp6B').value = localStorage.getItem("rp6B");			
			document.getElementById('1stBot').value = localStorage.getItem("1stBot");
			document.getElementById('2ndBot').value = localStorage.getItem("2ndBot");
			document.getElementById('3rdBot').value = localStorage.getItem("3rdBot");
			document.getElementById('4thBot').value = localStorage.getItem("4thBot");
			document.getElementById('5thBot').value = localStorage.getItem("5thBot");
			document.getElementById('6thBot').value = localStorage.getItem("6thBot");
			document.getElementById('7thBot').value = localStorage.getItem("7thBot");
			document.getElementById('8thBot').value = localStorage.getItem("8thBot");
			document.getElementById('9thBot').value = localStorage.getItem("9thBot");
			document.getElementById('bot1').value = localStorage.getItem("bot1");
			document.getElementById('bot2').value = localStorage.getItem("bot2");
			document.getElementById('bot3').value = localStorage.getItem("bot3");
			document.getElementById('bot4').value = localStorage.getItem("bot4");
			document.getElementById('bot5').value = localStorage.getItem("bot5");
			document.getElementById('bot6').value = localStorage.getItem("bot6");
			document.getElementById('bot7').value = localStorage.getItem("bot7");
			document.getElementById('bot8').value = localStorage.getItem("bot8");
			document.getElementById('bot9').value = localStorage.getItem("bot9");			
			document.getElementById('b1inn1B').value = localStorage.getItem("b1inn1B");
			document.getElementById('b1inn2B').value = localStorage.getItem("b1inn2B");
			document.getElementById('b1inn3B').value = localStorage.getItem("b1inn3B");
			document.getElementById('b1inn4B').value = localStorage.getItem("b1inn4B");
			document.getElementById('b1inn5B').value = localStorage.getItem("b1inn5B");
			document.getElementById('b1inn6B').value = localStorage.getItem("b1inn6B");
			document.getElementById('b1inn7B').value = localStorage.getItem("b1inn7B");
			document.getElementById('b1inn8B').value = localStorage.getItem("b1inn8B");
			document.getElementById('b1inn9B').value = localStorage.getItem("b1inn9B");
			document.getElementById('b1inn10B').value = localStorage.getItem("b1inn10B");
			document.getElementById('b1inn11B').value = localStorage.getItem("b1inn11B");
			document.getElementById('b1inn12B').value = localStorage.getItem("b1inn12B");			
			document.getElementById('b2inn1B').value = localStorage.getItem("b2inn1B");
			document.getElementById('b2inn2B').value = localStorage.getItem("b2inn2B");
			document.getElementById('b2inn3B').value = localStorage.getItem("b2inn3B");
			document.getElementById('b2inn4B').value = localStorage.getItem("b2inn4B");
			document.getElementById('b2inn5B').value = localStorage.getItem("b2inn5B");
			document.getElementById('b2inn6B').value = localStorage.getItem("b2inn6B");
			document.getElementById('b2inn7B').value = localStorage.getItem("b2inn7B");
			document.getElementById('b2inn8B').value = localStorage.getItem("b2inn8B");
			document.getElementById('b2inn9B').value = localStorage.getItem("b2inn9B");
			document.getElementById('b2inn10B').value = localStorage.getItem("b2inn10B");
			document.getElementById('b2inn11B').value = localStorage.getItem("b2inn11B");
			document.getElementById('b2inn12B').value = localStorage.getItem("b2inn12B");			
			document.getElementById('b3inn1B').value = localStorage.getItem("b3inn1B");
			document.getElementById('b3inn2B').value = localStorage.getItem("b3inn2B");
			document.getElementById('b3inn3B').value = localStorage.getItem("b3inn3B");
			document.getElementById('b3inn4B').value = localStorage.getItem("b3inn4B");
			document.getElementById('b3inn5B').value = localStorage.getItem("b3inn5B");
			document.getElementById('b3inn6B').value = localStorage.getItem("b3inn6B");
			document.getElementById('b3inn7B').value = localStorage.getItem("b3inn7B");
			document.getElementById('b3inn8B').value = localStorage.getItem("b3inn8B");
			document.getElementById('b3inn9B').value = localStorage.getItem("b3inn9B");
			document.getElementById('b3inn10B').value = localStorage.getItem("b3inn10B");
			document.getElementById('b3inn11B').value = localStorage.getItem("b3inn11B");
			document.getElementById('b3inn12B').value = localStorage.getItem("b3inn12B");			
			document.getElementById('b4inn1B').value = localStorage.getItem("b4inn1B");
			document.getElementById('b4inn2B').value = localStorage.getItem("b4inn2B");
			document.getElementById('b4inn3B').value = localStorage.getItem("b4inn3B");
			document.getElementById('b4inn4B').value = localStorage.getItem("b4inn4B");
			document.getElementById('b4inn5B').value = localStorage.getItem("b4inn5B");
			document.getElementById('b4inn6B').value = localStorage.getItem("b4inn6B");
			document.getElementById('b4inn7B').value = localStorage.getItem("b4inn7B");
			document.getElementById('b4inn8B').value = localStorage.getItem("b4inn8B");
			document.getElementById('b4inn9B').value = localStorage.getItem("b4inn9B");
			document.getElementById('b4inn10B').value = localStorage.getItem("b4inn10B");
			document.getElementById('b4inn11B').value = localStorage.getItem("b4inn11B");
			document.getElementById('b4inn12B').value = localStorage.getItem("b4inn12B");			
			document.getElementById('b5inn1B').value = localStorage.getItem("b5inn1B");
			document.getElementById('b5inn2B').value = localStorage.getItem("b5inn2B");
			document.getElementById('b5inn3B').value = localStorage.getItem("b5inn3B");
			document.getElementById('b5inn4B').value = localStorage.getItem("b5inn4B");
			document.getElementById('b5inn5B').value = localStorage.getItem("b5inn5B");
			document.getElementById('b5inn6B').value = localStorage.getItem("b5inn6B");
			document.getElementById('b5inn7B').value = localStorage.getItem("b5inn7B");
			document.getElementById('b5inn8B').value = localStorage.getItem("b5inn8B");
			document.getElementById('b5inn9B').value = localStorage.getItem("b5inn9B");
			document.getElementById('b5inn10B').value = localStorage.getItem("b5inn10B");
			document.getElementById('b5inn11B').value = localStorage.getItem("b5inn11B");
			document.getElementById('b5inn12B').value = localStorage.getItem("b5inn12B");			
			document.getElementById('b6inn1B').value = localStorage.getItem("b6inn1B");
			document.getElementById('b6inn2B').value = localStorage.getItem("b6inn2B");
			document.getElementById('b6inn3B').value = localStorage.getItem("b6inn3B");
			document.getElementById('b6inn4B').value = localStorage.getItem("b6inn4B");
			document.getElementById('b6inn5B').value = localStorage.getItem("b6inn5B");
			document.getElementById('b6inn6B').value = localStorage.getItem("b6inn6B");
			document.getElementById('b6inn7B').value = localStorage.getItem("b6inn7B");
			document.getElementById('b6inn8B').value = localStorage.getItem("b6inn8B");
			document.getElementById('b6inn9B').value = localStorage.getItem("b6inn9B");
			document.getElementById('b6inn10B').value = localStorage.getItem("b6inn10B");
			document.getElementById('b6inn11B').value = localStorage.getItem("b6inn11B");
			document.getElementById('b6inn12B').value = localStorage.getItem("b6inn12B");			
			document.getElementById('b7inn1B').value = localStorage.getItem("b7inn1B");
			document.getElementById('b7inn2B').value = localStorage.getItem("b7inn2B");
			document.getElementById('b7inn3B').value = localStorage.getItem("b7inn3B");
			document.getElementById('b7inn4B').value = localStorage.getItem("b7inn4B");
			document.getElementById('b7inn5B').value = localStorage.getItem("b7inn5B");
			document.getElementById('b7inn6B').value = localStorage.getItem("b7inn6B");
			document.getElementById('b7inn7B').value = localStorage.getItem("b7inn7B");
			document.getElementById('b7inn8B').value = localStorage.getItem("b7inn8B");
			document.getElementById('b7inn9B').value = localStorage.getItem("b7inn9B");
			document.getElementById('b7inn10B').value = localStorage.getItem("b7inn10B");
			document.getElementById('b7inn11B').value = localStorage.getItem("b7inn11B");
			document.getElementById('b7inn12B').value = localStorage.getItem("b7inn12B");			
			document.getElementById('b8inn1B').value = localStorage.getItem("b8inn1B");
			document.getElementById('b8inn2B').value = localStorage.getItem("b8inn2B");
			document.getElementById('b8inn3B').value = localStorage.getItem("b8inn3B");
			document.getElementById('b8inn4B').value = localStorage.getItem("b8inn4B");
			document.getElementById('b8inn5B').value = localStorage.getItem("b8inn5B");
			document.getElementById('b8inn6B').value = localStorage.getItem("b8inn6B");
			document.getElementById('b8inn7B').value = localStorage.getItem("b8inn7B");
			document.getElementById('b8inn8B').value = localStorage.getItem("b8inn8B");
			document.getElementById('b8inn9B').value = localStorage.getItem("b8inn9B");
			document.getElementById('b8inn10B').value = localStorage.getItem("b8inn10B");
			document.getElementById('b8inn11B').value = localStorage.getItem("b8inn11B");
			document.getElementById('b8inn12B').value = localStorage.getItem("b8inn12B");		
			document.getElementById('b9inn1B').value = localStorage.getItem("b9inn1B");
			document.getElementById('b9inn2B').value = localStorage.getItem("b9inn2B");
			document.getElementById('b9inn3B').value = localStorage.getItem("b9inn3B");
			document.getElementById('b9inn4B').value = localStorage.getItem("b9inn4B");
			document.getElementById('b9inn5B').value = localStorage.getItem("b9inn5B");
			document.getElementById('b9inn6B').value = localStorage.getItem("b9inn6B");
			document.getElementById('b9inn7B').value = localStorage.getItem("b9inn7B");
			document.getElementById('b9inn8B').value = localStorage.getItem("b9inn8B");
			document.getElementById('b9inn9B').value = localStorage.getItem("b9inn9B");
			document.getElementById('b9inn10B').value = localStorage.getItem("b9inn10B");
			document.getElementById('b9inn11B').value = localStorage.getItem("b9inn11B");
			document.getElementById('b9inn12B').value = localStorage.getItem("b9inn12B");
			
		}