/**
 * 
 */
function StorefunctionT() {
			//localStorage.clear();		
			localStorage.setItem("ballsT", document.getElementById('baT').value);
			localStorage.setItem("strikesT", document.getElementById('stT').value);
			localStorage.setItem("foulsT", document.getElementById('fbT').value);
			localStorage.setItem("teamT", document.getElementById('teamtop').value);
			localStorage.setItem("pitcherT", document.getElementById('pitchertop').value);
			localStorage.setItem("rp1T", document.getElementById('rp1T').value);
			localStorage.setItem("rp2T", document.getElementById('rp2T').value);
			localStorage.setItem("rp3T", document.getElementById('rp3T').value);
			localStorage.setItem("rp4T", document.getElementById('rp4T').value);
			localStorage.setItem("rp5T", document.getElementById('rp5T').value);
			localStorage.setItem("rp6T", document.getElementById('rp6T').value);
			localStorage.setItem("1stTop", document.getElementById('1stTop').value);
			localStorage.setItem("2ndTop", document.getElementById('2ndTop').value);
			localStorage.setItem("3rdTop", document.getElementById('3rdTop').value);
			localStorage.setItem("4thTop", document.getElementById('4thTop').value);
			localStorage.setItem("5thTop", document.getElementById('5thTop').value);
			localStorage.setItem("6thTop", document.getElementById('6thTop').value);
			localStorage.setItem("7thTop", document.getElementById('7thTop').value);
			localStorage.setItem("8thTop", document.getElementById('8thTop').value);
			localStorage.setItem("9thTop", document.getElementById('9thTop').value);
			localStorage.setItem("top1", document.getElementById('top1').value);
			localStorage.setItem("top2", document.getElementById('top2').value);
			localStorage.setItem("top3", document.getElementById('top3').value);
			localStorage.setItem("top4", document.getElementById('top4').value);
			localStorage.setItem("top5", document.getElementById('top5').value);
			localStorage.setItem("top6", document.getElementById('top6').value);
			localStorage.setItem("top7", document.getElementById('top7').value);
			localStorage.setItem("top8", document.getElementById('top8').value);
			localStorage.setItem("top9", document.getElementById('top9').value);		
			localStorage.setItem("b1inn1T", document.getElementById('b1inn1T').value);
			localStorage.setItem("b1inn2T", document.getElementById('b1inn2T').value);
			localStorage.setItem("b1inn3T", document.getElementById('b1inn3T').value);
			localStorage.setItem("b1inn4T", document.getElementById('b1inn4T').value);
			localStorage.setItem("b1inn5T", document.getElementById('b1inn5T').value);
			localStorage.setItem("b1inn6T", document.getElementById('b1inn6T').value);
			localStorage.setItem("b1inn7T", document.getElementById('b1inn7T').value);
			localStorage.setItem("b1inn8T", document.getElementById('b1inn8T').value);
			localStorage.setItem("b1inn9T", document.getElementById('b1inn9T').value);
			localStorage.setItem("b1inn10T", document.getElementById('b1inn10T').value);
			localStorage.setItem("b1inn11T", document.getElementById('b1inn11T').value);
			localStorage.setItem("b1inn12T", document.getElementById('b1inn12T').value);			
			localStorage.setItem("b2inn1T", document.getElementById('b2inn1T').value);
			localStorage.setItem("b2inn2T", document.getElementById('b2inn2T').value);
			localStorage.setItem("b2inn3T", document.getElementById('b2inn3T').value);
			localStorage.setItem("b2inn4T", document.getElementById('b2inn4T').value);
			localStorage.setItem("b2inn5T", document.getElementById('b2inn5T').value);
			localStorage.setItem("b2inn6T", document.getElementById('b2inn6T').value);
			localStorage.setItem("b2inn7T", document.getElementById('b2inn7T').value);
			localStorage.setItem("b2inn8T", document.getElementById('b2inn8T').value);
			localStorage.setItem("b2inn9T", document.getElementById('b2inn9T').value);
			localStorage.setItem("b2inn10T", document.getElementById('b2inn10T').value);
			localStorage.setItem("b2inn11T", document.getElementById('b2inn11T').value);
			localStorage.setItem("b2inn12T", document.getElementById('b2inn12T').value);			
			localStorage.setItem("b3inn1T", document.getElementById('b3inn1T').value);
			localStorage.setItem("b3inn2T", document.getElementById('b3inn2T').value);
			localStorage.setItem("b3inn3T", document.getElementById('b3inn3T').value);
			localStorage.setItem("b3inn4T", document.getElementById('b3inn4T').value);
			localStorage.setItem("b3inn5T", document.getElementById('b3inn5T').value);
			localStorage.setItem("b3inn6T", document.getElementById('b3inn6T').value);
			localStorage.setItem("b3inn7T", document.getElementById('b3inn7T').value);
			localStorage.setItem("b3inn8T", document.getElementById('b3inn8T').value);
			localStorage.setItem("b3inn9T", document.getElementById('b3inn9T').value);
			localStorage.setItem("b3inn10T", document.getElementById('b3inn10T').value);
			localStorage.setItem("b3inn11T", document.getElementById('b3inn11T').value);
			localStorage.setItem("b3inn12T", document.getElementById('b3inn12T').value);			
			localStorage.setItem("b4inn1T", document.getElementById('b4inn1T').value);
			localStorage.setItem("b4inn2T", document.getElementById('b4inn2T').value);
			localStorage.setItem("b4inn3T", document.getElementById('b4inn3T').value);
			localStorage.setItem("b4inn4T", document.getElementById('b4inn4T').value);
			localStorage.setItem("b4inn5T", document.getElementById('b4inn5T').value);
			localStorage.setItem("b4inn6T", document.getElementById('b4inn6T').value);
			localStorage.setItem("b4inn7T", document.getElementById('b4inn7T').value);
			localStorage.setItem("b4inn8T", document.getElementById('b4inn8T').value);
			localStorage.setItem("b4inn9T", document.getElementById('b4inn9T').value);
			localStorage.setItem("b4inn10T", document.getElementById('b4inn10T').value);
			localStorage.setItem("b4inn11T", document.getElementById('b4inn11T').value);
			localStorage.setItem("b4inn12T", document.getElementById('b4inn12T').value);			
			localStorage.setItem("b5inn1T", document.getElementById('b5inn1T').value);
			localStorage.setItem("b5inn2T", document.getElementById('b5inn2T').value);
			localStorage.setItem("b5inn3T", document.getElementById('b5inn3T').value);
			localStorage.setItem("b5inn4T", document.getElementById('b5inn4T').value);
			localStorage.setItem("b5inn5T", document.getElementById('b5inn5T').value);
			localStorage.setItem("b5inn6T", document.getElementById('b5inn6T').value);
			localStorage.setItem("b5inn7T", document.getElementById('b5inn7T').value);
			localStorage.setItem("b5inn8T", document.getElementById('b5inn8T').value);
			localStorage.setItem("b5inn9T", document.getElementById('b5inn9T').value);
			localStorage.setItem("b5inn10T", document.getElementById('b5inn10T').value);
			localStorage.setItem("b5inn11T", document.getElementById('b5inn11T').value);
			localStorage.setItem("b5inn12T", document.getElementById('b5inn12T').value);			
			localStorage.setItem("b6inn1T", document.getElementById('b6inn1T').value);
			localStorage.setItem("b6inn2T", document.getElementById('b6inn2T').value);
			localStorage.setItem("b6inn3T", document.getElementById('b6inn3T').value);
			localStorage.setItem("b6inn4T", document.getElementById('b6inn4T').value);
			localStorage.setItem("b6inn5T", document.getElementById('b6inn5T').value);
			localStorage.setItem("b6inn6T", document.getElementById('b6inn6T').value);
			localStorage.setItem("b6inn7T", document.getElementById('b6inn7T').value);
			localStorage.setItem("b6inn8T", document.getElementById('b6inn8T').value);
			localStorage.setItem("b6inn9T", document.getElementById('b6inn9T').value);
			localStorage.setItem("b6inn10T", document.getElementById('b6inn10T').value);
			localStorage.setItem("b6inn11T", document.getElementById('b6inn11T').value);
			localStorage.setItem("b6inn12T", document.getElementById('b6inn12T').value);			
			localStorage.setItem("b7inn1T", document.getElementById('b7inn1T').value);
			localStorage.setItem("b7inn2T", document.getElementById('b7inn2T').value);
			localStorage.setItem("b7inn3T", document.getElementById('b7inn3T').value);
			localStorage.setItem("b7inn4T", document.getElementById('b7inn4T').value);
			localStorage.setItem("b7inn5T", document.getElementById('b7inn5T').value);
			localStorage.setItem("b7inn6T", document.getElementById('b7inn6T').value);
			localStorage.setItem("b7inn7T", document.getElementById('b7inn7T').value);
			localStorage.setItem("b7inn8T", document.getElementById('b7inn8T').value);
			localStorage.setItem("b7inn9T", document.getElementById('b7inn9T').value);
			localStorage.setItem("b7inn10T", document.getElementById('b7inn10T').value);
			localStorage.setItem("b7inn11T", document.getElementById('b7inn11T').value);
			localStorage.setItem("b7inn12T", document.getElementById('b7inn12T').value);			
			localStorage.setItem("b8inn1T", document.getElementById('b8inn1T').value);
			localStorage.setItem("b8inn2T", document.getElementById('b8inn2T').value);
			localStorage.setItem("b8inn3T", document.getElementById('b8inn3T').value);
			localStorage.setItem("b8inn4T", document.getElementById('b8inn4T').value);
			localStorage.setItem("b8inn5T", document.getElementById('b8inn5T').value);
			localStorage.setItem("b8inn6T", document.getElementById('b8inn6T').value);
			localStorage.setItem("b8inn7T", document.getElementById('b8inn7T').value);
			localStorage.setItem("b8inn8T", document.getElementById('b8inn8T').value);
			localStorage.setItem("b8inn9T", document.getElementById('b8inn9T').value);
			localStorage.setItem("b8inn10T", document.getElementById('b8inn10T').value);
			localStorage.setItem("b8inn11T", document.getElementById('b8inn11T').value);
			localStorage.setItem("b8inn12T", document.getElementById('b8inn12T').value);			
			localStorage.setItem("b9inn1T", document.getElementById('b9inn1T').value);
			localStorage.setItem("b9inn2T", document.getElementById('b9inn2T').value);
			localStorage.setItem("b9inn3T", document.getElementById('b9inn3T').value);
			localStorage.setItem("b9inn4T", document.getElementById('b9inn4T').value);
			localStorage.setItem("b9inn5T", document.getElementById('b9inn5T').value);
			localStorage.setItem("b9inn6T", document.getElementById('b9inn6T').value);
			localStorage.setItem("b9inn7T", document.getElementById('b9inn7T').value);
			localStorage.setItem("b9inn8T", document.getElementById('b9inn8T').value);
			localStorage.setItem("b9inn9T", document.getElementById('b9inn9T').value);
			localStorage.setItem("b9inn10T", document.getElementById('b9inn10T').value);
			localStorage.setItem("b9inn11T", document.getElementById('b9inn11T').value);
			localStorage.setItem("b9inn12T", document.getElementById('b9inn12T').value);		
		}
		
		function recallStoreT() {
			document.getElementById('baT').value = localStorage.getItem("ballsT");
			document.getElementById('stT').value = localStorage.getItem("strikesT");
			document.getElementById('fbT').value = localStorage.getItem("foulsT");
			document.getElementById('teamtop').value = localStorage.getItem("teamT");
			document.getElementById('pitchertop').value = localStorage.getItem("pitcherT");
			document.getElementById('rp1T').value = localStorage.getItem("rp1T");
			document.getElementById('rp2T').value = localStorage.getItem("rp2T");
			document.getElementById('rp3T').value = localStorage.getItem("rp3T");
			document.getElementById('rp4T').value = localStorage.getItem("rp4T");
			document.getElementById('rp5T').value = localStorage.getItem("rp5T");
			document.getElementById('rp6T').value = localStorage.getItem("rp6T");			
			document.getElementById('1stTop').value = localStorage.getItem("1stTop");
			document.getElementById('2ndTop').value = localStorage.getItem("2ndTop");
			document.getElementById('3rdTop').value = localStorage.getItem("3rdTop");
			document.getElementById('4thTop').value = localStorage.getItem("4thTop");
			document.getElementById('5thTop').value = localStorage.getItem("5thTop");
			document.getElementById('6thTop').value = localStorage.getItem("6thTop");
			document.getElementById('7thTop').value = localStorage.getItem("7thTop");
			document.getElementById('8thTop').value = localStorage.getItem("8thTop");
			document.getElementById('9thTop').value = localStorage.getItem("9thTop");
			document.getElementById('top1').value = localStorage.getItem("top1");
			document.getElementById('top2').value = localStorage.getItem("top2");
			document.getElementById('top3').value = localStorage.getItem("top3");
			document.getElementById('top4').value = localStorage.getItem("top4");
			document.getElementById('top5').value = localStorage.getItem("top5");
			document.getElementById('top6').value = localStorage.getItem("top6");
			document.getElementById('top7').value = localStorage.getItem("top7");
			document.getElementById('top8').value = localStorage.getItem("top8");
			document.getElementById('top9').value = localStorage.getItem("top9");			
			document.getElementById('b1inn1T').value = localStorage.getItem("b1inn1T");
			document.getElementById('b1inn2T').value = localStorage.getItem("b1inn2T");
			document.getElementById('b1inn3T').value = localStorage.getItem("b1inn3T");
			document.getElementById('b1inn4T').value = localStorage.getItem("b1inn4T");
			document.getElementById('b1inn5T').value = localStorage.getItem("b1inn5T");
			document.getElementById('b1inn6T').value = localStorage.getItem("b1inn6T");
			document.getElementById('b1inn7T').value = localStorage.getItem("b1inn7T");
			document.getElementById('b1inn8T').value = localStorage.getItem("b1inn8T");
			document.getElementById('b1inn9T').value = localStorage.getItem("b1inn9T");
			document.getElementById('b1inn10T').value = localStorage.getItem("b1inn10T");
			document.getElementById('b1inn11T').value = localStorage.getItem("b1inn11T");
			document.getElementById('b1inn12T').value = localStorage.getItem("b1inn12T");			
			document.getElementById('b2inn1T').value = localStorage.getItem("b2inn1T");
			document.getElementById('b2inn2T').value = localStorage.getItem("b2inn2T");
			document.getElementById('b2inn3T').value = localStorage.getItem("b2inn3T");
			document.getElementById('b2inn4T').value = localStorage.getItem("b2inn4T");
			document.getElementById('b2inn5T').value = localStorage.getItem("b2inn5T");
			document.getElementById('b2inn6T').value = localStorage.getItem("b2inn6T");
			document.getElementById('b2inn7T').value = localStorage.getItem("b2inn7T");
			document.getElementById('b2inn8T').value = localStorage.getItem("b2inn8T");
			document.getElementById('b2inn9T').value = localStorage.getItem("b2inn9T");
			document.getElementById('b2inn10T').value = localStorage.getItem("b2inn10T");
			document.getElementById('b2inn11T').value = localStorage.getItem("b2inn11T");
			document.getElementById('b2inn12T').value = localStorage.getItem("b2inn12T");			
			document.getElementById('b3inn1T').value = localStorage.getItem("b3inn1T");
			document.getElementById('b3inn2T').value = localStorage.getItem("b3inn2T");
			document.getElementById('b3inn3T').value = localStorage.getItem("b3inn3T");
			document.getElementById('b3inn4T').value = localStorage.getItem("b3inn4T");
			document.getElementById('b3inn5T').value = localStorage.getItem("b3inn5T");
			document.getElementById('b3inn6T').value = localStorage.getItem("b3inn6T");
			document.getElementById('b3inn7T').value = localStorage.getItem("b3inn7T");
			document.getElementById('b3inn8T').value = localStorage.getItem("b3inn8T");
			document.getElementById('b3inn9T').value = localStorage.getItem("b3inn9T");
			document.getElementById('b3inn10T').value = localStorage.getItem("b3inn10T");
			document.getElementById('b3inn11T').value = localStorage.getItem("b3inn11T");
			document.getElementById('b3inn12T').value = localStorage.getItem("b3inn12T");			
			document.getElementById('b4inn1T').value = localStorage.getItem("b4inn1T");
			document.getElementById('b4inn2T').value = localStorage.getItem("b4inn2T");
			document.getElementById('b4inn3T').value = localStorage.getItem("b4inn3T");
			document.getElementById('b4inn4T').value = localStorage.getItem("b4inn4T");
			document.getElementById('b4inn5T').value = localStorage.getItem("b4inn5T");
			document.getElementById('b4inn6T').value = localStorage.getItem("b4inn6T");
			document.getElementById('b4inn7T').value = localStorage.getItem("b4inn7T");
			document.getElementById('b4inn8T').value = localStorage.getItem("b4inn8T");
			document.getElementById('b4inn9T').value = localStorage.getItem("b4inn9T");
			document.getElementById('b4inn10T').value = localStorage.getItem("b4inn10T");
			document.getElementById('b4inn11T').value = localStorage.getItem("b4inn11T");
			document.getElementById('b4inn12T').value = localStorage.getItem("b4inn12T");			
			document.getElementById('b5inn1T').value = localStorage.getItem("b5inn1T");
			document.getElementById('b5inn2T').value = localStorage.getItem("b5inn2T");
			document.getElementById('b5inn3T').value = localStorage.getItem("b5inn3T");
			document.getElementById('b5inn4T').value = localStorage.getItem("b5inn4T");
			document.getElementById('b5inn5T').value = localStorage.getItem("b5inn5T");
			document.getElementById('b5inn6T').value = localStorage.getItem("b5inn6T");
			document.getElementById('b5inn7T').value = localStorage.getItem("b5inn7T");
			document.getElementById('b5inn8T').value = localStorage.getItem("b5inn8T");
			document.getElementById('b5inn9T').value = localStorage.getItem("b5inn9T");
			document.getElementById('b5inn10T').value = localStorage.getItem("b5inn10T");
			document.getElementById('b5inn11T').value = localStorage.getItem("b5inn11T");
			document.getElementById('b5inn12T').value = localStorage.getItem("b5inn12T");			
			document.getElementById('b6inn1T').value = localStorage.getItem("b6inn1T");
			document.getElementById('b6inn2T').value = localStorage.getItem("b6inn2T");
			document.getElementById('b6inn3T').value = localStorage.getItem("b6inn3T");
			document.getElementById('b6inn4T').value = localStorage.getItem("b6inn4T");
			document.getElementById('b6inn5T').value = localStorage.getItem("b6inn5T");
			document.getElementById('b6inn6T').value = localStorage.getItem("b6inn6T");
			document.getElementById('b6inn7T').value = localStorage.getItem("b6inn7T");
			document.getElementById('b6inn8T').value = localStorage.getItem("b6inn8T");
			document.getElementById('b6inn9T').value = localStorage.getItem("b6inn9T");
			document.getElementById('b6inn10T').value = localStorage.getItem("b6inn10T");
			document.getElementById('b6inn11T').value = localStorage.getItem("b6inn11T");
			document.getElementById('b6inn12T').value = localStorage.getItem("b6inn12T");			
			document.getElementById('b7inn1T').value = localStorage.getItem("b7inn1T");
			document.getElementById('b7inn2T').value = localStorage.getItem("b7inn2T");
			document.getElementById('b7inn3T').value = localStorage.getItem("b7inn3T");
			document.getElementById('b7inn4T').value = localStorage.getItem("b7inn4T");
			document.getElementById('b7inn5T').value = localStorage.getItem("b7inn5T");
			document.getElementById('b7inn6T').value = localStorage.getItem("b7inn6T");
			document.getElementById('b7inn7T').value = localStorage.getItem("b7inn7T");
			document.getElementById('b7inn8T').value = localStorage.getItem("b7inn8T");
			document.getElementById('b7inn9T').value = localStorage.getItem("b7inn9T");
			document.getElementById('b7inn10T').value = localStorage.getItem("b7inn10T");
			document.getElementById('b7inn11T').value = localStorage.getItem("b7inn11T");
			document.getElementById('b7inn12T').value = localStorage.getItem("b7inn12T");			
			document.getElementById('b8inn1T').value = localStorage.getItem("b8inn1T");
			document.getElementById('b8inn2T').value = localStorage.getItem("b8inn2T");
			document.getElementById('b8inn3T').value = localStorage.getItem("b8inn3T");
			document.getElementById('b8inn4T').value = localStorage.getItem("b8inn4T");
			document.getElementById('b8inn5T').value = localStorage.getItem("b8inn5T");
			document.getElementById('b8inn6T').value = localStorage.getItem("b8inn6T");
			document.getElementById('b8inn7T').value = localStorage.getItem("b8inn7T");
			document.getElementById('b8inn8T').value = localStorage.getItem("b8inn8T");
			document.getElementById('b8inn9T').value = localStorage.getItem("b8inn9T");
			document.getElementById('b8inn10T').value = localStorage.getItem("b8inn10T");
			document.getElementById('b8inn11T').value = localStorage.getItem("b8inn11T");
			document.getElementById('b8inn12T').value = localStorage.getItem("b8inn12T");		
			document.getElementById('b9inn1T').value = localStorage.getItem("b9inn1T");
			document.getElementById('b9inn2T').value = localStorage.getItem("b9inn2T");
			document.getElementById('b9inn3T').value = localStorage.getItem("b9inn3T");
			document.getElementById('b9inn4T').value = localStorage.getItem("b9inn4T");
			document.getElementById('b9inn5T').value = localStorage.getItem("b9inn5T");
			document.getElementById('b9inn6T').value = localStorage.getItem("b9inn6T");
			document.getElementById('b9inn7T').value = localStorage.getItem("b9inn7T");
			document.getElementById('b9inn8T').value = localStorage.getItem("b9inn8T");
			document.getElementById('b9inn9T').value = localStorage.getItem("b9inn9T");
			document.getElementById('b9inn10T').value = localStorage.getItem("b9inn10T");
			document.getElementById('b9inn11T').value = localStorage.getItem("b9inn11T");
			document.getElementById('b9inn12T').value = localStorage.getItem("b9inn12T");
			
		}